#  encoding: utf8
#  reconnect: false
#  database: go
#  username: hesdev
#  password: hesdev
#  host: localhost
#  socket: /Applications/MAMP/tmp/mysql/mysql.sock

# development:
#    adapter: mysql2
#    encoding: utf8
#    database: kaa_development
#    username: hesdev
#    password: l0ngd@y
#    host: 10.100.1.249

#vagrant development
development:
   host: localhost
   adapter: mysql2
   encoding: utf8
   database: kaa_development
   username: hesdev
   password:

test:
    adapter: mysql2
    encoding: utf8
    database: kaa_test
    username: hesdev
    password: l0ngd@y
    host: 10.100.1.249
